In [71]:
# ex-1 loan installment calculation
loan = float(input('Loan amount: '))
salary = float(input('Buyer salary: '))
years = float(input('Number of years to pay: '))

installment = loan / (years * 12)
maxValue = salary * 0.3

if installment > maxValue:
    print(f'Loan denied. The installment of ${installment:.2f} exceeds 30% of the salary (${maxValue:.2f}).')
else:
    print(f'Loan approved. The monthly installment will be ${installment:.2f} and the duration will be {years:.0f} years.')


Loan denied. The installment of $85.72 exceeds 30% of the salary ($37.20).


In [72]:
# ex-2 final purchase value calculation
purchaseValue = float(input('Purchase value: '))
installments = int(input('Number of installments: '))

if installments == 1:
    finalValue = purchaseValue * 0.9
    print(f'Final value: {finalValue} with payment option in {installments} installment')
elif installments == 2:
    finalValue = purchaseValue
    print(f'Final value: {finalValue} with payment option in {installments} installments')
else:
    finalValue = purchaseValue * 1.20
    print(f'Final value: {finalValue} with payment option in {installments} installments')

Final value: 1234.0 with payment option in 2 installments


In [73]:
# ex-3 rock paper scissors
# 1 rock
# 2 paper
# 3 scissors
import numpy as np

wins = 0
for n in range(10):
    choice = int(input('Choice: 1 for rock, 2 for paper, 3 for scissors: '))
    pcRandom = np.random.randint(1, 4)
    if choice == 1 and pcRandom == 3:
        print('You won! You chose rock and the computer chose scissors')
        wins += 1
    elif choice == 2 and pcRandom == 1:
        print('You won! You chose paper and the computer chose rock')
        wins += 1
    elif choice == 3 and pcRandom == 2:
        print('You won! You chose scissors and the computer chose paper')
        wins += 1
    else:
        print('You lost!')
print(f'You won {wins} times! Win rate: {wins/10:.2f}%')

You lost!
You won! You chose paper and the computer chose rock
You won! You chose scissors and the computer chose paper
You won! You chose paper and the computer chose rock
You lost!
You lost!
You lost!
You won! You chose scissors and the computer chose paper
You won! You chose rock and the computer chose scissors
You lost!
You won 5 times! Win rate: 0.50%


In [74]:
# ex-4 lê valores positivos, sem repetir, até digitar um negativo
# ex-4 read positive values, without repetition, until a negative is entered
values = []

while True:
    value = float(input('Insert positive values or a negative number to stop: '))
    if value < 0:
        break

    if value in values:
        print('Value already inserted, it will not be added again.')
    else:
        values.append(value)

# if the list is not empty, show results
if values:
    qty = len(values)
    smallest = min(values)
    largest = max(values)
    pos_smallest = values.index(smallest)
    pos_largest = values.index(largest)

    print(f'{qty} non-repeated values were inserted.')
    print(f'The smallest value is {smallest:.2f} at position {pos_smallest}.')
    print(f'The largest value is {largest:.2f} at position {pos_largest}.')
else:
    print('No valid values were inserted.')

Value already inserted, it will not be added again.
5 non-repeated values were inserted.
The smallest value is 1.00 at position 2.
The largest value is 213124.00 at position 4.


In [75]:
# ex-5
numbers = []
for n in range(5):
    number = float(input('Insert a number: '))
    numbers.append(number)
numbers.sort()
print(f'Sorted list: {numbers}')

Sorted list: [123.0, 123.0, 123.0, 123.0, 123.0]


In [77]:
# ex-6
even_list = []
odd_list = []

for i in range(10):
    value = int(input(f'Enter the {i+1}th integer value: '))
    if value % 2 == 0:
        even_list.append(value)
    else:
        odd_list.append(value)

even_list.sort(reverse=True)
odd_list.sort(reverse=True)

print(f'Even values in descending order: {even_list}')
print(f'Odd values in descending order: {odd_list}')

Even values in descending order: [10, 8, 6, 4, 2]
Odd values in descending order: [9, 7, 5, 3, 1]


In [78]:
# ex-7
import numpy as np

dim = int(input('Input the matrix dimension: '))

matrix = np.zeros((dim, dim), dtype=int)

for i in range(dim):
    for j in range(dim):
        matrix[i, j] = int(input(f'Input the value for position [{i}][{j}]: '))

print(matrix)
print(f'Sum of even values: {matrix[matrix % 2 == 0].sum()}')
print(f'Sum of values in the third column: {matrix[:, 2].sum() if dim > 2 else 999999}')
print(f'Smallest value in the second row: {matrix[1].min() if dim > 1 else 999999}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of even values: 20
Sum of values in the third column: 18
Smallest value in the second row: 4


In [79]:
# ex-8

# list of students
students = []

while True:
    # list with number, name, grades and average of each student
    student = []
    studentNumber = int(input('Input the student number: '))
    studentName = input('Input the student name: ')

    # grades 1, 2 and average
    grades = []
    average = 0

    # loop to input the 2 grades
    for i in range(2):
        grade = float(input(f'Input grade {i+1} for {studentName}: '))
        average += grade
        grades.append(grade)
    average /= 2

    # add average to the grades list
    grades.append(average)

    # add student info to the main list
    student.append(studentNumber)
    student.append(studentName)
    student.append(grades)

    students.append(student)

    # ask if want to add more students
    stop = input('More students? (y/n): ')
    if stop == 'n':
        break

# print the list of students with their info
for s in students:
    print(f'Number: {s[0]}, Name: {s[1]}, Grades: {s[2][0]:.2f}, {s[2][1]:.2f}, Average: {s[2][2]:.2f}')


Number: 123, Name: a, Grades: 12.00, 14.00, Average: 13.00
Number: 321, Name: b, Grades: 11.00, 13.00, Average: 12.00


In [83]:
# ex-9
def counter(start, end, step):
    list = []
    for i in range(1, 11, 1):
        list.append(i)
    print(list)
    list = []
    for i in range(10, -1, -2):
        list.append(i)
    print(list)
    list = []
    for i in range(start, end + 1, step):
        list.append(i)
    print(list)

start = int(input('Input the start number: '))
end = int(input('Input the end number: '))
step = int(input('Input the step: '))

counter(start, end, step)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 8, 6, 4, 2, 0]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33]


In [ ]:
# ex-10
import numpy as np

def greater(values):
    greatest = float('-inf')
    for i in range(len(values)):
        if values[i] > greatest:
            greatest = values[i]
    return greatest

values = np.random.randint(0, 100, size=15, dtype=int)
print(values)
print(greater(values))

In [84]:
# ex-10.2 using (*values)

import numpy as np

def greater(*values):
    greatest = float('-inf')
    for i in range(len(values)):
        if values[i] > greatest:
            greatest = values[i]
    return greatest

values = np.random.randint(0, 100, size=15, dtype=int)
print(values)
print(greater(*values))

[77 15 92 12 29 59 36 58 23 40 25 80 34 81  6]
92
