In [ ]:
a = input('escreva um numero ')
b = input('escreva um numero ')
print(f'a soma entre {a} e {b} eh {a + b}')

In [3]:
a = int(input('escreva um numero '))
b = int(input('escreva um numero '))
print(f'a soma entre {a} e {b} eh {a + b}')

escreva um numero 1
escreva um numero 2
a soma entre 1 e 2 eh 3


In [4]:
a = int(input('Escreva um numero inteiro:'))
b = float(input('Escreva um numero:'))
print(f'A soma entre o numero {a} e o numero {b:.3f} eh {a + b:.3f}')

Escreva um numero inteiro:1
Escreva um numero:2.123
A soma entre o numero 1 e o numero 2.123 eh 3.123


In [1]:
import numpy as np
for n in range (3,11,3):
    print(f'a raiz quadrada de {n} eh {np.sqrt(n):.2f}')
    
# formato RANGE(INICIO, FIM + 1, PASSO)
for n in range (5):
    print(f'range 5 = {n}')
    
for n in range (3,9):
    print(f'range 3,9 = {n}')
    
for n in range (1,8,2):
    print(f'range 1,8,2 = {n}')

a raiz quadrada de 3 eh 1.73
a raiz quadrada de 6 eh 2.45
a raiz quadrada de 9 eh 3.00
range 5 = 0
range 5 = 1
range 5 = 2
range 5 = 3
range 5 = 4
range 3,9 = 3
range 3,9 = 4
range 3,9 = 5
range 3,9 = 6
range 3,9 = 7
range 3,9 = 8
range 1,8,2 = 1
range 1,8,2 = 3
range 1,8,2 = 5
range 1,8,2 = 7


In [17]:
def soma(a,b):
    return a+b

a = float(input('escreva um float: '))
b = float(input('escreva outro float: '))
s = soma(a,b)
print(f'a soma entre {a} e {b} eh igual a {s}')

escreva um float: 3.2
escreva outro float: 2.3
a soma entre 3.2 e 2.3 eh igual a 5.5


In [ ]:
# teste de bibliotecas no pycharm com o venv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dados = np.array([10, 20, 30, 40, 50])

df = pd.DataFrame(dados, columns=["valores"])

print("Média:", df["valores"].mean())

plt.plot(df["valores"])
plt.show()

In [5]:
# ex-1 calculo de valor de parcela de emprestimo
emprestimo = float(input('Valor do empréstimo: '))
salario = float(input('Salario do comprador: '))
anos = float(input('Quantidade de anos para pagar: '))

parcela = emprestimo / (anos * 12)
valorMax = salario * 0.3

if parcela > valorMax:
    print(f'Empréstimo negado. A parcela de R${parcela:.2f} excede 30% do salário ({valorMax:.2f}).')
else:
    print(f'Empréstimo aprovado. A parcela mensal será de {parcela:.2f} e a duração sera de {anos:.0f} anos.')

Empréstimo negado. A parcela de R$833.33 excede 30% do salário (360.00).


In [11]:
# ex-2 calculo de valor final de compra
valorCompra = float(input('Valor da compra: '))
parcelas = int(input('Quantidade de parcelas: '))

if parcelas == 1:
    valorFinal = valorCompra * 0.9
    print(f'valor sera de: {valorFinal} com opção de pagamento em {parcelas} parcelas')
elif parcelas == 2:
    valorFinal = valorCompra
    print(f'valor sera de: {valorFinal} com opção de pagamento em {parcelas} parcelas')
else:
    valorFinal = valorCompra * 1.20
    print(f'valor sera de: {valorFinal} com opção de pagamento em {parcelas} parcelas')


valor sera de: 900.0 com opção de pagamento em 1 parcelas


In [23]:
# ex-3 pedra papel e tesoura
# 1 pedra
# 2 papel
# 3 tesoura
vitorias = 0
for n in range(10):
    escolha = int(input('Escolha: 1 para pedra, 2 para papel, 3 para tesoura: '))
    pcRandom = np.random.randint(1,4)
    if escolha == 1 and pcRandom == 3:
        print('Voce ganhou! escolheu pedra e o pc escolheu tesoura')
        vitorias += 1
    elif escolha == 2 and pcRandom == 1:
        print('Voce ganhou! escolheu papel e o pc escolheu pedra')
        vitorias += 1
    elif escolha == 3 and pcRandom == 2:
        print('Voce ganhou! escolheu tesoura e o pc escolheu papel')
        vitorias += 1
    else:
        print('Voce perdeu!')
print(f'Voce ganhou {vitorias} vezes! taxa de vitoria de {vitorias/10:.2f}%')

Voce ganhou! escolheu pedra e o pc escolheu tesoura
Voce ganhou! escolheu papel e o pc escolheu pedra
Voce ganhou! escolheu tesoura e o pc escolheu papel
Voce ganhou! escolheu tesoura e o pc escolheu papel
Voce ganhou! escolheu papel e o pc escolheu pedra
Voce ganhou! escolheu pedra e o pc escolheu tesoura
Voce perdeu!
Voce perdeu!
Voce perdeu!
Voce perdeu!
Voce ganhou 6 vezes! taxa de vitoria de 0.60%


In [26]:
# ex-4 lê valores positivos, sem repetir, até digitar um negativo
valores = []

while True:
    valor = float(input('Insira valores positivos ou um negativo para parar: '))
    if valor < 0:
        break

    if valor in valores:
        print('Valor já inserido, não será adicionado de novo.')
    else:
        valores.append(valor)

# se a lista não estiver vazia, mostra os resultados
if valores:
    qtd = len(valores)
    menor = min(valores)
    maior = max(valores)
    pos_menor = valores.index(menor)
    pos_maior = valores.index(maior)

    print(f'Foram inseridos {qtd} valores não repetidos.')
    print(f'O menor valor é {menor:.2f} na posição {pos_menor}.')
    print(f'O maior valor é {maior:.2f} na posição {pos_maior}.')
else:
    print('Nenhum valor válido foi inserido.')

Valor já inserido, não será adicionado de novo.
Valor já inserido, não será adicionado de novo.
Valor já inserido, não será adicionado de novo.
Foram inseridos 8 valores não repetidos.
O menor valor é 1.00 na posição 0.
O maior valor é 4124.00 na posição 7.


In [28]:
# ex-5
lista = []
for n in range (5):
    numero = float(input('insira um numero: '))
    lista.append(numero)
lista.sort()
print(f'Lista ordenada: {lista}')

Lista ordenada: [1.0, 2.0, 3.0, 4.0, 5.0]


In [35]:
# ex-6
lista_par = []
lista_impar = []

for i in range(10):
    valor = int(input(f'Digite o {i+1}º valor inteiro: '))
    if valor % 2 == 0:
        lista_par.append(valor)
    else:
        lista_impar.append(valor)

lista_par.sort(reverse=True)
lista_impar.sort(reverse=True)

print(f'Valores pares em ordem decrescente: {lista_par}')
print(f'Valores ímpares em ordem decrescente: {lista_impar}')

Valores pares em ordem decrescente: [10, 8, 6, 4, 2]
Valores ímpares em ordem decrescente: [9, 7, 5, 3, 1]


In [27]:
# ex-7
import numpy as np

dim = int(input('Input the matrix dimension: '))

matrix = np.zeros((dim, dim), dtype=int)

for i in range(dim):
    for j in range(dim):
        matrix[i,j] = int(input(f'Input the value for position [{i}][{j}]: '))

print(matrix)
print(f'Sum of even values: {matrix[matrix % 2 == 0].sum()}')
print(f'Sum of values in the third column: {matrix[:, 2].sum() if dim > 2 else 999999}')
print(f'Minor value in the second row: {matrix[1].min() if dim > 1 else 999999}')

[[1 2]
 [3 4]]
Sum of even values: 6
Sum of values in the third column: 999999
Minor value in the second row: 3


In [65]:
# ex-8

# list of students
students = []

while True:
    # list with number, name, grades and median of each student
    student = []
    studentNumber = int(input('Input the student number: '))
    studentName = input('Input the student name: ')

    # grades 1, 2 and median
    grades = []
    median = 0

    # loop to input the 2 grades
    for i in range(2):
        grade = float(input(f'Input the grade {i+1} for {studentName}: '))
        median += grade
        grades.append(grade)
    median /= 2

    # add median to the grades list
    grades.append(median)

    # add student info to the main list
    student.append(studentNumber)
    student.append(studentName)
    student.append(grades)

    students.append(student)

    # ask if want to add more students
    stop = input('More students? (y/n): ')
    if stop == 'n':
        break

# print the list of students with their info
for s in students:
    print(f'Number: {s[0]}, Name: {s[1]}, Grades: {s[2][0]:.2f}, {s[2][1]:.2f}, Median: {s[2][2]:.2f}')



[[123, 'a', [12.0, 14.0, 13.0]], [321, 'b', [11.0, 13.0, 12.0]]]
Number: 123, Name: a, Grades: 12.00, 14.00, Median: 13.00
Number: 321, Name: b, Grades: 11.00, 13.00, Median: 12.00


In [67]:
# ex-9
def counter(start, end, step):
    for i in range(1,11,1):
        print(i)
    for i in range(10,0,-2):
        print(i)
    for i in range(start, end+1, step):
        print(i)

start = int(input('Input the start number: '))
end = int(input('Input the end number: '))
step = int(input('Input the step: '))

counter(start, end, step)

1
2
3
4
5
6
7
8
9
10
10
8
6
4
2
0
3
6
9
12
15
18
21
24
27
30
33


In [59]:
# ex-10
import numpy as np

def greater(values):
    greater = float('-inf')
    for i in range(len(values)):
        if values[i] > greater:
            greater = values[i]
    return greater

values = np.random.randint(0, 100, size=15, dtype=int)
print(values)
print(greater(values))

[ 6 53 12 39 60 78 81 62  8  7 45 94 19 11 84]
94


In [51]:
# ex 10.2 using ((* values))

import numpy as np

def greater(* values):
    greater = float('-inf')
    for i in range(len(values)):
        if values[i] > greater:
            greater = values[i]
    return greater

values = np.random.randint(0, 100, size=15, dtype=int)
print(values)
print(greater(* values))

[48 56 17 63 75 69 40 55 44 73 32 66 32 30 85]
85
